'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating concise safety notes for medications.
 *
 * The flow takes a medication name and optional additional information as input and returns safety notes generated by the Gemini API.
 *
 * @Exported Types:
 *   - GenerateSafetyNotesInput: The input type for the generateSafetyNotes function.
 *   - GenerateSafetyNotesOutput: The output type for the generateSafetyNotes function.
 *   - generateSafetyNotes: The exported function to generate safety notes.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSafetyNotesInputSchema = z.object({
  medicationName: z.string().describe('The name of the medication.'),
  additionalInformation: z
    .string()
    .optional()
    .describe('Additional information to consider when generating safety notes.'),
});

export type GenerateSafetyNotesInput = z.infer<typeof GenerateSafetyNotesInputSchema>;

const GenerateSafetyNotesOutputSchema = z.object({
  safetyNotes: z.string().describe('Concise safety notes for the medication.'),
});

export type GenerateSafetyNotesOutput = z.infer<typeof GenerateSafetyNotesOutputSchema>;

export async function generateSafetyNotes(
  input: GenerateSafetyNotesInput
): Promise<GenerateSafetyNotesOutput> {
  return generateSafetyNotesFlow(input);
}

const generateSafetyNotesPrompt = ai.definePrompt({
  name: 'generateSafetyNotesPrompt',
  input: {schema: GenerateSafetyNotesInputSchema},
  output: {schema: GenerateSafetyNotesOutputSchema},
  prompt: `You are a helpful AI assistant specializing in providing concise and easy-to-understand safety notes for medications.

  Given the medication name and any additional information, generate safety notes that cover important precautions, potential side effects, dosage timing and food instructions in simple language.

  Medication Name: {{{medicationName}}}
  Additional Information: {{{additionalInformation}}}

  Safety Notes:`,
});

const generateSafetyNotesFlow = ai.defineFlow(
  {
    name: 'generateSafetyNotesFlow',
    inputSchema: GenerateSafetyNotesInputSchema,
    outputSchema: GenerateSafetyNotesOutputSchema,
  },
  async input => {
    const {output} = await generateSafetyNotesPrompt(input);
    return output!;
  }
);
