"use client";

import * as React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Stethoscope, 
  Loader2, 
  Activity, 
  CheckCircle2, 
  AlertTriangle, 
  AlertCircle,
  History, 
  ShieldCheck,
  ChevronDown,
  Info,
  Calendar,
  Sparkles,
  Bot,
  Brain,
  MessageSquare
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { useUser, useFirestore, useCollection, useMemoFirebase, addDocumentNonBlocking } from '@/firebase';
import { query, collection, orderBy, limit } from 'firebase/firestore';
import { checkSymptoms, CheckSymptomsOutput } from '@/ai/flows/check-symptoms';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { formatDistanceToNow } from 'date-fns';

export default function SymptomCheckerPage() {
  const { user } = useUser();
  const firestore = useFirestore();
  const { toast } = useToast();
  
  const [isAnalyzing, setIsAnalyzing] = React.useState(false);
  const [analysis, setAnalysis] = React.useState<CheckSymptomsOutput | null>(null);
  const [input, setInput] = React.useState("");

  const checksQuery = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return query(
      collection(firestore, "users", user.uid, "symptomChecks"),
      orderBy("createdAt", "desc"),
      limit(15)
    );
  }, [firestore, user?.uid]);

  const { data: history, isLoading: historyLoading } = useCollection(checksQuery);

  const handleCheck = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!input.trim() || isAnalyzing) return;

    setIsAnalyzing(true);
    setAnalysis(null);

    try {
      const result = await checkSymptoms({ symptoms: input });
      setAnalysis(result);
      
      if (user && firestore) {
        addDocumentNonBlocking(collection(firestore, "users", user.uid, "symptomChecks"), {
          ...result,
          userInput: input,
          userId: user.uid,
          createdAt: new Date().toISOString(),
        });
      }

      toast({
        title: "Triage Complete",
        description: "Preliminary health guidance generated by AI Diagnostic node.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Triage Node Error",
        description: "AI failed to process clinical input. Please retry.",
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'Emergency': return 'text-red-500 bg-red-50 border-red-200 shadow-[0_0_20px_rgba(239,68,68,0.2)]';
      case 'High Risk': return 'text-orange-600 bg-orange-50 border-orange-200';
      case 'Moderate Risk': return 'text-blue-600 bg-blue-50 border-blue-200';
      case 'Low Risk': return 'text-emerald-600 bg-emerald-50 border-emerald-200';
      default: return 'text-slate-500 bg-slate-50';
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="p-4 sm:p-10 space-y-10 pb-24 max-w-[1400px] mx-auto font-body"
    >
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
           <div className="flex items-center gap-3 mb-1">
             <div className="p-2 bg-primary/10 rounded-xl">
               <Stethoscope className="size-5 text-primary" />
             </div>
             <span className="text-[10px] font-black uppercase tracking-[0.3em] text-primary/60">AI Triage Node v4.1</span>
           </div>
           <h1 className="text-4xl font-black tracking-tighter text-foreground">Symptom Checker</h1>
           <p className="text-muted-foreground font-medium">Preliminary health analysis based on clinical AI diagnostic logic.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-8 space-y-8">
           <Card className="border-none shadow-2xl bg-white rounded-[2.5rem] overflow-hidden">
              <CardHeader className="p-10 pb-6 border-b bg-slate-50/50">
                 <div className="flex items-center gap-4">
                    <div className="size-12 rounded-2xl bg-primary flex items-center justify-center text-white shadow-xl shadow-primary/20">
                       <MessageSquare className="size-6" />
                    </div>
                    <div>
                       <CardTitle className="text-2xl font-black uppercase tracking-tight">Clinical Intake</CardTitle>
                       <CardDescription className="font-bold">Describe what you are feeling in simple terms.</CardDescription>
                    </div>
                 </div>
              </CardHeader>
              <CardContent className="p-10">
                 <form onSubmit={handleCheck} className="space-y-6">
                    <div className="relative">
                       <Textarea 
                         placeholder="e.g. I have a sharp pain in my lower back that started 2 hours ago..."
                         className="min-h-[200px] rounded-[2rem] p-8 border-2 focus-visible:ring-primary/20 text-lg leading-relaxed bg-slate-50/30"
                         value={input}
                         onChange={(e) => setInput(e.target.value)}
                         disabled={isAnalyzing}
                       />
                       <div className="absolute bottom-6 right-6 flex items-center gap-3">
                          <p className="text-[10px] font-black uppercase tracking-widest text-slate-300">Minimum 10 characters</p>
                          <Button 
                            size="lg" 
                            type="submit"
                            disabled={input.length < 10 || isAnalyzing}
                            className="h-16 px-10 rounded-2xl font-black uppercase text-[11px] tracking-widest shadow-2xl shadow-primary/20 hover:scale-105 transition-transform"
                          >
                            {isAnalyzing ? <Loader2 className="animate-spin mr-2" /> : <Sparkles className="size-4 mr-2" />}
                            Check Symptoms
                          </Button>
                       </div>
                    </div>
                 </form>
              </CardContent>
           </Card>

           <AnimatePresence mode="wait">
             {isAnalyzing && (
               <motion.div key="processing" initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} className="p-20 bg-white border-2 border-dashed border-primary/20 rounded-[3rem] text-center space-y-8 shadow-2xl">
                  <div className="relative mx-auto size-32">
                     <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 2, ease: "linear" }} className="absolute inset-0 border-4 border-primary border-t-transparent rounded-full opacity-20" />
                     <motion.div animate={{ scale: [1, 1.2, 1] }} transition={{ repeat: Infinity, duration: 1.5 }} className="absolute inset-0 flex items-center justify-center">
                        <Brain className="size-16 text-primary" />
                     </motion.div>
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-3xl font-black uppercase tracking-tighter">Diagnostic Engine Processing</h3>
                    <p className="text-xs font-bold text-muted-foreground uppercase tracking-[0.3em] animate-pulse">Running Multi-Agent Triage Algorithms...</p>
                  </div>
                  <div className="max-w-xs mx-auto">
                     <Progress value={65} className="h-1.5" />
                  </div>
               </motion.div>
             )}

             {analysis && !isAnalyzing && (
               <motion.div key="analysis-view" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-8">
                 <Card className={cn("border-none shadow-2xl rounded-[3rem] overflow-hidden bg-white", analysis.riskLevel === 'Emergency' ? 'ring-4 ring-red-500 ring-offset-4 ring-offset-background' : '')}>
                    <CardHeader className="bg-slate-900 text-white p-10 relative overflow-hidden">
                       <div className="absolute top-0 right-0 p-10 opacity-10"><ShieldCheck className="size-48" /></div>
                       <div className="relative z-10 space-y-6">
                          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                             <div className="space-y-1">
                                <Badge className={cn("font-black text-[10px] tracking-widest border-none px-5 py-2 rounded-full", getRiskColor(analysis.riskLevel))}>
                                   {analysis.riskLevel.toUpperCase()}
                                </Badge>
                                <h2 className="text-4xl font-black tracking-tighter mt-4">Triage Results</h2>
                             </div>
                             {analysis.riskLevel === 'Emergency' && (
                                <motion.div animate={{ scale: [1, 1.05, 1] }} transition={{ repeat: Infinity, duration: 1 }} className="p-6 rounded-[2rem] bg-red-500 text-white border-2 border-white/20 shadow-2xl flex items-center gap-4">
                                   <AlertTriangle className="size-10" />
                                   <div>
                                      <p className="text-[10px] font-black uppercase tracking-widest opacity-80">Immediate Action Required</p>
                                      <p className="text-lg font-black uppercase tracking-tighter">Seek Urgent Care</p>
                                   </div>
                                </motion.div>
                             )}
                          </div>
                       </div>
                    </CardHeader>
                    <CardContent className="p-10 space-y-10">
                       {analysis.emergencyWarning && (
                          <div className="p-8 rounded-[2.5rem] bg-red-50 border-2 border-red-100 flex items-start gap-6 shadow-sm">
                             <div className="size-14 rounded-2xl bg-red-500 text-white flex items-center justify-center shrink-0 shadow-lg">
                                <AlertCircle className="size-8" />
                             </div>
                             <div className="space-y-1">
                                <h4 className="text-xl font-black text-red-900 tracking-tight uppercase">Emergency Warning</h4>
                                <p className="text-sm font-bold text-red-800 leading-relaxed italic">"{analysis.emergencyWarning}"</p>
                             </div>
                          </div>
                       )}

                       <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                          <div className="space-y-6">
                             <h4 className="text-[11px] font-black uppercase tracking-[0.4em] text-primary flex items-center gap-2">
                               <Activity className="size-4" /> Possible Conditions
                             </h4>
                             <div className="space-y-4">
                                {analysis.possibleConditions.map((cond, i) => (
                                  <div key={i} className="p-6 rounded-[2rem] border-2 border-slate-50 bg-slate-50/50 space-y-3 group hover:border-primary/20 transition-all shadow-sm">
                                     <div className="flex justify-between items-center">
                                        <p className="font-black text-lg uppercase tracking-tighter">{cond.name}</p>
                                        <Badge variant="outline" className="font-black text-[9px] border-primary/20 text-primary">{cond.confidence}% Match</Badge>
                                     </div>
                                     <p className="text-xs font-medium text-muted-foreground leading-relaxed italic">"{cond.explanation}"</p>
                                  </div>
                                ))}
                             </div>
                          </div>
                          <div className="space-y-6">
                             <h4 className="text-[11px] font-black uppercase tracking-[0.4em] text-primary flex items-center gap-2">
                               <CheckCircle2 className="size-4" /> Recommended Steps
                             </h4>
                             <div className="space-y-3">
                                {analysis.recommendedActions.map((action, i) => (
                                  <div key={i} className="p-5 rounded-2xl bg-white border-2 border-slate-100 flex items-center gap-4 group hover:scale-[1.02] transition-transform">
                                     <div className="size-8 rounded-xl bg-primary/5 text-primary flex items-center justify-center font-black text-xs shrink-0">{i + 1}</div>
                                     <p className="text-sm font-bold text-slate-800 leading-none">{action}</p>
                                  </div>
                                ))}
                             </div>
                          </div>
                       </div>

                       <div className="space-y-6">
                          <h4 className="text-[11px] font-black uppercase tracking-[0.4em] text-slate-400">Triage Intelligence Matrix</h4>
                          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                             <div className="p-6 rounded-[2rem] bg-slate-900 text-white space-y-4 shadow-xl">
                                <h5 className="text-[10px] font-black uppercase tracking-widest text-primary">Symptoms Identified</h5>
                                <div className="flex flex-wrap gap-2">
                                   {analysis.identifiedSymptoms.map((s, i) => (
                                     <Badge key={i} className="bg-white/10 text-white font-black text-[9px] uppercase border-none h-6 px-3">{s}</Badge>
                                   ))}
                                </div>
                             </div>
                             <div className="p-6 rounded-[2rem] bg-slate-50 border-2 border-slate-100 space-y-4 col-span-1 sm:col-span-2">
                                <h5 className="text-[10px] font-black uppercase tracking-widest text-slate-400">Clinical Follow-up Questions</h5>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                   {analysis.followUpQuestions.map((q, i) => (
                                      <div key={i} className="flex items-start gap-3">
                                         <div className="size-1.5 bg-primary rounded-full mt-1.5 shrink-0" />
                                         <p className="text-xs font-medium text-slate-600 leading-relaxed italic">{q}</p>
                                      </div>
                                   ))}
                                </div>
                             </div>
                          </div>
                       </div>

                       <div className="bg-destructive/5 border-2 border-destructive/10 p-8 rounded-[2.5rem] flex items-start gap-6">
                          <div className="size-12 rounded-2xl bg-destructive/10 text-destructive flex items-center justify-center shrink-0">
                             <Info className="size-6" />
                          </div>
                          <div className="space-y-1">
                             <h5 className="font-black text-xs uppercase tracking-widest text-destructive">Clinical Disclaimer</h5>
                             <p className="text-xs font-medium text-destructive/80 leading-relaxed italic">
                               This is not a medical diagnosis. The HealthAI Symptom Checker provides preliminary health guidance based on clinical AI logic and large medical records datasets. Always consult a licensed healthcare professional for official diagnosis and treatment.
                             </p>
                          </div>
                       </div>
                    </CardContent>
                 </Card>
               </motion.div>
             )}
           </AnimatePresence>
        </div>

        <div className="lg:col-span-4 space-y-8">
           <Card className="border-none shadow-2xl bg-white rounded-[2.5rem] overflow-hidden flex flex-col max-h-[850px]">
              <CardHeader className="p-8 border-b bg-slate-50">
                 <div className="flex items-center justify-between">
                    <CardTitle className="text-xl font-black uppercase tracking-tighter flex items-center gap-3">
                       <History className="size-6 text-primary" /> Triage History
                    </CardTitle>
                    <Badge variant="outline" className="text-[8px] font-black uppercase tracking-widest">{history?.length || 0} Archived</Badge>
                 </div>
              </CardHeader>
              <CardContent className="flex-1 overflow-y-auto p-8 space-y-4 clinical-scrollbar">
                 {historyLoading ? (
                   <div className="flex justify-center py-10 opacity-20"><Loader2 className="animate-spin" /></div>
                 ) : !history || history.length === 0 ? (
                   <div className="text-center py-20 opacity-30 italic">No historical triage sessions.</div>
                 ) : (
                   history.map((check) => (
                     <motion.div 
                        initial={{ opacity: 0 }} 
                        animate={{ opacity: 1 }} 
                        key={check.id} 
                        onClick={() => { setAnalysis(check as any); setInput(check.userInput); }}
                        className="p-5 rounded-[2rem] border-2 bg-slate-50 hover:bg-white hover:border-primary transition-all cursor-pointer group shadow-sm"
                     >
                        <div className="flex items-center gap-4 mb-3">
                           <div className={cn(
                             "size-10 rounded-xl flex items-center justify-center text-white shadow-lg", 
                             check.riskLevel === 'Emergency' ? 'bg-red-500' : 'bg-primary'
                           )}>
                              <Bot className="size-4" />
                           </div>
                           <div className="min-w-0 pr-4">
                              <h4 className="text-sm font-black uppercase tracking-tighter truncate leading-none mb-1">{check.userInput.substring(0, 40)}...</h4>
                              <p className="text-[8px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1">
                                <Calendar className="size-2.5" /> {formatDistanceToNow(new Date(check.createdAt), { addSuffix: true })}
                              </p>
                           </div>
                        </div>
                        <div className="flex items-center justify-between">
                           <div className="flex gap-2">
                              <Badge className={cn("font-black text-[7px] uppercase tracking-widest h-5", getRiskColor(check.riskLevel))}>{check.riskLevel}</Badge>
                              <Badge className="bg-slate-900 text-white font-black text-[7px] uppercase tracking-widest h-5">{check.identifiedSymptoms?.length || 0} SYMPTOMS</Badge>
                           </div>
                           <ChevronDown className="size-3 text-slate-300 group-hover:text-primary transition-colors" />
                        </div>
                     </motion.div>
                   ))
                 )}
              </CardContent>
           </Card>

           <Card className="border-none bg-slate-900 text-white rounded-[2.5rem] p-10 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-8 opacity-20 group-hover:scale-125 transition-transform duration-1000">
                 <Bot className="size-32 text-primary" />
              </div>
              <div className="relative z-10 space-y-6">
                 <h4 className="text-2xl font-black uppercase tracking-tighter">Clinical Logic</h4>
                 <p className="text-sm font-medium text-white/70 leading-relaxed">
                    Our AI Triage Node cross-references symptoms against established medical protocols and common physiological patterns to assess immediate risk.
                 </p>
                 <div className="p-5 bg-white/5 rounded-2xl border border-dashed border-white/20">
                    <p className="text-[10px] font-black uppercase tracking-widest text-primary mb-2 flex items-center gap-2">
                       <ShieldCheck className="size-3" /> Secure Diagnostics
                    </p>
                    <p className="text-[11px] leading-relaxed opacity-60">
                       Assessment occurs in your isolated clinical node. No data is shared with external providers without consent.
                    </p>
                 </div>
              </div>
           </Card>
        </div>
      </div>
    </motion.div>
  );
}
